version: '3.4'

services:
  nginx:
    image: nginx:1.21
    env_file:
      - .env.prod
    volumes:
      - ./docker/nginx.dev.conf:/etc/nginx/templates/default.conf.template:ro
      - ./:/app
    ports:
      - ${APP_PORT:-80}:80
      - ${APP_SSL_PORT:-443}:443
    networks:
      - appnet
    depends_on:
      - backend
  backend:
    build:
      context: ./
      target: prod
    env_file:
      - .env.prod
    links:
      - db
    networks:
      - appnet
    depends_on:
      - db
  db:
    image: postgres:${DB_SERVER_VERSION:-15}-alpine
    environment:
      - POSTGRES_PASSWORD=${DB_PASSWORD:-!PasswordByDefault!}
      - POSTGRES_USER=${DB_USER:-app}
      - POSTGRES_DB=${DB_NAME:-db_name}
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - appnet

networks:
  appnet:
    driver: bridge

volumes:
  pgdata:
